### ISSUE TITLE
`internal` and `final`

### ISSUE THREAD

**Issue by Wuchiwei** [royhsu/swift-style-guide#1]
![image](https://user-images.githubusercontent.com/16999468/31107269-ee85c7ae-a7b6-11e7-8b1a-755255b950b1.png)

Internal level access control is default setting in swift.
Final pre-fix will be add by compiler in build time.

These two rules seem to be unnecessary.

Is it better change to mark not internal and final class instead of mark every class and property?

**Comment by royhsu** [comment]
@Wuchiwei I knew it, but these have been well-considered by me. Just follow the guide to implement them.

Usually for readability reason.

**Comment by royhsu** [comment]
@Wuchiwei 
FYI. [Increasing Performance by Reducing Dynamic Dispatch](https://developer.apple.com/swift/blog/?id=27)

**Comment by Wuchiwei** [comment]
Roger that.
